### ISSUE TITLE
Callable Bind only supports no-parameter Call

### ISSUE THREAD

**Issue by scgm0** [raulsntos/godot-dotnet#5] opened 2024-04-07 13:11 UTC
### Godot version

v4.3.dev.mono.custom_build [de932f29d]

### Godot .NET packages version

https://github.com/raulsntos/godot-dotnet/commit/f6c04004fb9a82b56cfa71ab51133f2f37b29bbf

### System information

Godot v4.3.dev.mono (de932f29d) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 06 Apr 2024 23:01:55 +0000 - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 550.67) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### .NET information

8.0.203

### Issue description

Callable Bind will crash directly when using Call with parameters.
Code that runs fine：
```
Callable.From<int, int>((a, b) => GD.Print(a + b))
    .Bind([5, 6])
    .Call();
```
Running code that crashes：
```
Callable.From<int, int>((a, b) => GD.Print(a + b))
    .Bind([5, 6])
    .Call([0, 0]);
```

### Steps to reproduce

```
Callable.From<int, int>((a, b) => GD.Print(a + b))
    .Bind([5, 6])
    .Call([0, 0]);
```

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment] 2024-04-08 00:11
- Sounds like a duplicate of #4 that was recently fixed.

You didn't specify what version of the Godot .NET packages you are using, it seems you just copied the Godot version. So I don't know if this is a nightly build or a custom build. There are no nightly builds with the fix, you'll have to make a custom build for now (use commit f6c04004fb9a82b56cfa71ab51133f2f37b29bbf or newer).

**Comment by raulsntos** [comment] 2024-04-08 17:21
Yes, it's expected behavior. You have a Callable with 2 parameters, when you use `Bind` you are essentially assigning values to those parameters already so when you use `Call` you have to pass only the remaining parameters.

```csharp
Callable callable = Callable.From<int, int, int>((a, b, c) => GD.Print(a + b + c));

callable.Call([1, 2, 3]); // Must pass 3 parameters.

callable.Bind([3]).Call([1, 2]); // Must pass 2 parameters, because we already bound 1.

callable.Bind([2, 3]).Call([1]); // Must pass 1 parameter, because we already bound 2.

callable.Bind([1, 2, 3]).Call(); // Must not pass any parameters, because we already bound them all.
```

**Closed** 2024-04-08 17:27 UTC
